### ISSUE TITLE
PhET code style

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#10]
Related to #1 (code review).

>  - [ ] Is the code formatted according to PhET conventions? See [phet-idea-code-style.xml](https://github.com/phetsims/phet-info/blob/master/ide/idea/phet-idea-codestyle.xml) for IntelliJ IDEA code style.

Since this is your own repository, this is somewhat irrelevant.  But I thought I'd provide more info, in case you're interested.  

PhET's code style is codified in phet-idea-codestyle.xml, which is a configuration file for use with IntelliJ IDEA or WebStorm.  If you're using either one of those IDEs, then you can set up a "Code Style" by importing phet-idea-codestyle.xml, and the IDE will format code using that style.   If you're using Sublime, there might be some other process that I'm not familiar with, and I'd refer you to one of the other PhET developers (a couple of them us Sublime).   If you're using some other IDE, then you're sort of on your own. 

If you want to do nothing, that's of course OK too.

**Comment by heldentodd** [comment]
To be honest, I've been using MS Visual Studio Code because it was free and easy to install when I was getting started. I think it's time I switch to IntelliJ IDEA or WebStorm. I'm researching them now. Any recommendation between the two?

**Comment by pixelzoom** [comment]
WebStorm is a subset of IDEA, and their user interfaces are almost identical. The typical advice is: Use IDEA if you're working with Java and JavaScript.  Use WebStorm is you're working with JavaScript exclusively.  

On the other hand, IDEA Community Edition is free for use by open-source projects. WebStorm has no such free version, and you'll need to purchase a license.  So you might consider starting with IDEA Community Edition.

Regardless of which product you choose, PhET has useful information in https://github.com/phetsims/phet-info/tree/master/ide/idea, including how to set up both IDEA and WebStorm for doing PhET sim development.

**Comment by heldentodd** [comment]
Thank you. I was just figuring that out. It turns out all the jetBrains products are free to me since I'm an educator! I'm installing WebStorm for now since it seems a bit simpler and should meet all my current needs. I will read the PhET information first.

**Comment by heldentodd** [comment]
OK, I've installed imported the PhET codestyle into webstorm. I did put the hardwrap a little past 120 with a guide at 120. Other than that, I don't see the difference yet. Hopefully my code will be prettier.

**Comment by pixelzoom** [comment]
FYI... Code formatting is not (by default) entirely automatic in WebStorm or IDEA.

If you haven't already, you'll need to ask WebStorm to reformat your existing code. Select your xray-diffraction repository in the Project View, then choose "Code > Reformat Code" from the menu bar.   You should see a dialog like this (you might want to check "Organize Imports" too):

<img width="451" alt="screenshot_378" src="https://user-images.githubusercontent.com/3046552/83950129-7aee2c00-a7e5-11ea-8bcc-22cbfe2716d6.png">

If you're using WebStorm to commit and push changes to GitHub, you can automatically format code by checking "Reformat Code" in the Commit Changes dialog, see screenshot below.  Otherwise you'll need to use the "Code > Reformat Code" menu item.

<img width="896" alt="screenshot_379" src="https://user-images.githubusercontent.com/3046552/83950157-be489a80-a7e5-11ea-94b8-c435a07d155c.png">

**Comment by heldentodd** [comment]
Great. I just reformatted all the code. It still looks recognizable to me.
Yes, Webstorm is handling all my github pushes. I don't think I could manage it otherwise.
