### ISSUE TITLE
use type-specific Properties

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#12]
Related to #1 (code review):

> - [ ] Properties should use type-specific subclasses where appropriate (.e.g BooleanProperty, NumberProperty, StringProperty) or provide documentation as to why they are not.

PhET provides type-specific Properties to help prevent the kinds of programming errors that are typical in weakly-types languages like JavaScript.   Some, like NumberProperty, provides options that assist with validation (see `isValidValue` and `range` options).

Searching for "new Property" in all .js files, I identified these opportunities to use type-specific Properties:

````js
// use NumberProperty
this.protractorAngleProperty = new Property( 0.0 );

// use BooleanProperty
this.showProtractorProperty = new Property( false );

// use Vector2Property
const protractorPositionProperty = new Property( protractorPosition );
basePositionProperty: new Property( new Vector2( 100, 100 ) ),
tipPositionProperty:  new Property( new Vector2( 140, 100 ) ),
```

**Comment by heldentodd** [comment]
Now using type-specific properties everywhere, except the special property for the tape measure
    const measuringTapeProperty = new Property( {name: 'Å', multiplier: 0.125} );
and some calls to multilink - for example:
    Property.multilink( [
      model.sourceWavelengthProperty,
      model.horizontalRaysProperty,
      model.verticalRaysProperty,
      model.showWaveFrontsProperty,
      model.pathDifferenceProperty
      ], () => { this.redrawLight(model, this.crystalNode); } );
