### ISSUE TITLE
bad suffix for DerivedProperty latticeConstantsP

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#14]
Related to #1 (code review):

> - [ ] Naming for Property values:  All `AXON/Property` instances should be declared with the suffix `Property`.  For example, if a visible property is added, it should have the name `visibleProperty` instead of simply `visible`.  This will help to avoid confusion with non-Property definitions.

Overall good on this, but this one should be `this.latticeConstantsProperty`:

```js
// Lattice.js
this.latticeConstantsP = new DerivedProperty( [this.aConstantProperty, this.bConstantProperty, this.cConstantProperty ], combineConstants );

**Comment by heldentodd** [comment]
Fixed. When I started, I just thought the name was getting too long.
