### ISSUE TITLE
misspelled param rotatable

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#17]
Related to #1 (code review).

In ProtractorNode.js:

```js
@param {boolean} rotateable - can be rotated
```

... should be spelled `rotatable`.

**Comment by heldentodd** [comment]
How do you see these things? I've fixed it in my copy. This should also be fixed in the Bending Light PhET (common/view/ProtractorNode.js).

Thanks.

**Comment by pixelzoom** [comment]
> How do you see these things? 

WebStorm marks things that are misspelled.  Note the green squiggle under "rotateable":

<img width="527" alt="screenshot_380" src="https://user-images.githubusercontent.com/3046552/83956518-30d46d00-a81c-11ea-8bfb-bab471b57657.png">
