### ISSUE TITLE
unused string

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#2]
Related to #1 (code review).

> - [ ] Does the sim build without warnings or errors?

There is one unused string that's identified during a build, recommenced to delete it:

```
% cd xray-diffraction
% grunt
...
>> Unused string: key=LatticeConstant, value=Lattice Constant
...
``

**Comment by heldentodd** [comment]
I was keeping this key because I might want it in the future.

After reflection, I've just deleted it.
