### ISSUE TITLE
unnecessary return statement 

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#20]
Related to #1 (code review).

Lattice `updateSites` does not need a `return` statement.  WebStorm flags it as unnecessary.

**Comment by pixelzoom** [comment]
The documentation is also confusing and a bit messy.   It says "Returns an array of lattice points" but actually returns nothing.  I'm guessing that this is vestigial documentation, out of sync with the current implementation.

```js
    /**
     * put functions here
     * @public
     */

    updateSites() {
      /**
     * Returns an array of lattice points
     * @returns {Array}
     * @private
     */// Called when lattice constant changes or crystal rotates.

...
      return;
    }
  }
```

**Comment by heldentodd** [comment]
The return has been removed. I also updated the documentation comment.
