### ISSUE TITLE
documentation and visibility annotations for fields

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#22]
Related to #1 (code review).

See the "Visibility Annotations" subsection of #1, then take another pass through your code.  These are important because JavaScript lacks native visibility features, so you have to rely on documentation to know what the intended visibility is for fields, methods, etc.

For example, in Lattice.js, there are 3 fields that lack visibility annotations: `anglePhiProperty`, `reciprocalBasis`, `sites`.

In XrayDiffractionModel.js, there's only 1 field that has a visibility annotation: `stepEmitter`.  The other are undocumented.

**Comment by pixelzoom** [comment]
Documentation for fields is also a little sparse.  From #1:

>  - [ ] In common code repositories all options and fields should have type expressions, regardless of their visibility, and regardless whether their type is obvious from the context. If the same examples from above appeared in common code:  ...

Recommended to look at the examples that accompany that checklist item, and provide more detail about the semantics/purpose of each field.

**Comment by heldentodd** [comment]
I've added several visibility annotations (and others comments). I think the code is easier to understand now.
