### ISSUE TITLE
remove dead code

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#26]
Related to #1 (code review).

There are a few cases of "dead code", code that has been commented out, that should be attended to.  Here are a few, not necessarily and exhaustive list.

Lattice.js
```js
     //super( latticeConstants, orientation );

  //this.latticeConstantsP.reset();
```

XrayControlPanel.js
```js
  //const pathDifferenceProperty = new BooleanProperty ( false );

//const content = alignGroup.createBox( container );
```

XrayDiffractionScreenView.js
```js
  // baseDragStarted: () => { grabSound.play(); },

   // toolboxNodes = toolboxNodes.concat( this.getAdditionalToolIcons() );
```

XrayParametersPanel.js
```js
  //const ENERGY_FONT = new PhetFont( { size: 22, weight: 'bold' } );
```

**Comment by heldentodd** [comment]
I've been removing dead code all along. I did a search and found 2 more pieces of dead code. These have been deleted.
