### ISSUE TITLE
unnecessary coupling

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#31]
Related to #1 (code review).

>  - [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)
> - [ ] Is there too much unnecessary decoupling? (e.g. by passing all of the properties of an object independently instead of passing the object itself)?

XrayParameterPanel is an example of "unnecessary coupling".  The entire XrayDiffrationModel is passed into its constructor:

```js
    /**
     * @param {XrayDiffractionModel} model
     * @param {Object} [options]
     */
    constructor( model, options ) {
```

That gives XrayParameterPanel access to all 13 fields and 3 methods of XrayDiffrationModel, when in fact it only needs access to 3 fields (lattice, sourceAngleProperty, sourceWavelengthProperty) and 0 methods. 

To reduce coupling, change the signature of XrayParameterPanel's constructor to:

```js
    /**
     * @param {Lattice} lattice
     * @param {Property.<number>} sourceAngleProperty
     * @param {Property.<number>} sourceWavelengthProperty 
     * @param {Object} [options]
     */
    constructor( model, options ) {
```

and instantiate like this:

```js
this.controlPanel = new XrayControlPanel( model.lattice, model. sourceAngleProperty,  model. sourceWavelengthProperty );
```

CrystalNode also has potential for decoupling -- it only requires 2 fields of Lattice.

There is obviously a trade-off here, in that more constructor parameters are required. When the number of constructor parameters gets "unmanageably large", or when you're accessing "most' of an object's fields, then it's better to just pass in the entire object.  And sometimes it's a subjective decision that needs to be made at the developer's discretion.   

As an example of "unnecessary decoupling"....  XrayParameterPanel requires access to most of XrayDiffrationModel, so it's better to pass in the entire model instance.  Trying to pass in each field individually would be an example of unnecessary decoupling.

**Comment by pixelzoom** [comment]
I neglected to describe why unnecessary coupling is undesirable.  If you're unfamiliar with coupling and cohesion (in the context of programming) see https://en.wikipedia.org/wiki/Coupling_(computer_programming).

**Comment by heldentodd** [comment]
I can understand the advantage of decoupling. I'm very new to JavaScript, and passing the whole model made it so that I didn't have to figure out how variables work (scope, etc.). I think I've got it now. I was able to decouple a little more than you suggested. This also shortens some of the long lines in the code. The new constructors for XrayParameterPanel and CrystalNode are now:

```js
class XrayParameterPanel extends Panel {

  /**
   * @param {Property.<Vector3>} latticeConstantsProperty
   * @param {Property.<number>} sourceAngleProperty
   * @param {Property.<number>} sourceWavelengthProperty
   * @param {Object} [options]
   */
  constructor( latticeConstantsProperty, sourceAngleProperty, sourceWavelengthProperty, options ) {

class CrystalNode extends Node {
  /**
   * @param {Array.<Vector2>} sites - an Array of Vector2 points for the crystal lattice
   * @param {Vector3} latticeConstants
   */
  constructor( sites, latticeConstants ) {
```
