### ISSUE TITLE
copy of ProtectorNode

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#32]
Related to #1 (code review).

I noticed that ProtractorNode.js has this header:

```js
/**
 * Protractor node in 'Pendulum Lab' simulation.
 *
 * @author Andrey Zelenkov (Mlearner)
 */
```

So it's almost certainly a copy of pendulum-lab/ProtractorNode, which is a copy of bending-light/ProtractorNode.   Since there's clearly a need for a reusable version of ProtractorNode, I've created issue https://github.com/phetsims/scenery-phet/issues/609.  @heldentodd you might want to put a TODO in your copy of ProtractorNode.js that says something like:

```js
// TODO: replace this file when PhET has generalized ProtractorNode, see https://github.com/phetsims/scenery-phet/issues/609
```

**Comment by heldentodd** [comment]
Done. I copied this file from bending-light/ProtractorNode and have not modified the code (except to correct the misspelling you caught: rotateable to rotatable).

**Comment by pixelzoom** [comment]
I've made a note at https://github.com/phetsims/scenery-phet/issues/609#issuecomment-640288732 to fix the spelling (rotateable to rotatable) in whatever eventually gets generalized.
