### ISSUE TITLE
'a', 'b', 'd' strings are not localized

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#5]
Related to #1 (code review).

> - [ ] Are there any strings that are not internationalized, and does the sim layout gracefully handle internationalized strings that are shorter than the English strings? (run with query parameter `stringTest=X`. You should see nothing but 'X' strings.)

The strings 'a' and 'b' are localized in the control panel, but not in CrystalNode.js.  Here's what it looks like with `stringTest=X`:

<img width="1176" alt="screenshot_358" src="https://user-images.githubusercontent.com/3046552/83438944-726dae00-a3ff-11ea-88c6-1611d9577216.png">

So if someone translates your sim to another language, there will be a problem here. Recommended to move string literals 'a', 'b', and 'd' from CrystalNode.js to xray-diffraction-strings_en.json.

**Comment by heldentodd** [comment]
This is fixed. 

Originally, I thought a, b, and d would be universal abbreviations, but perhaps not, especially for d. I'm leaving sin(θ) and λ (for wavelength) hard coded because I really can't imagine those needing translation.

**Comment by pixelzoom** [comment]
Understood about 'a', 'b', 'd' possibly being universal abbreviations.  I should have clarified that PhET sometimes makes a similar call with math symbols.  And the problem here was that 'a' and 'b' were localized in one place (slider labels), but not in another (crystal).
