### ISSUE TITLE
layout problems with long strings

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#6]
Related to #1 (code review).

> - [ ] Does the sim layout gracefully handle internationalized strings that are twice as long as the English strings? (run with query parameter `stringTest=double`)
> 
> - [ ] Does the sim layout gracefully handle internationalized strings that are exceptionally long? (run with query parameter `stringTest=long`)

When your sim is translated in other languages, the lengths of strings may change significantly, and that can create layout problems that negatively impact the user experiences.   In the extreme cases, layout problems can even make the sim unusable. The above 2 checklist items ensure that your sim adapts to longer strings.

Here's a screenshot when running with `?dev&stringTest=long`.  `dev` draws a red rectangle that indicates the "safe area", or what PhET call the "layout bounds", which is the area that is guaranteed to be visible on all devices. If you draw anything outside of the layout bounds, then it will not be visible on some devices. 

<img width="1179" alt="screenshot_360" src="https://user-images.githubusercontent.com/3046552/83439498-86fe7600-a400-11ea-8840-a58a2ee9b9d1.png">

So in this sim, long strings cause a problem.  The way to address this problem is to set `maxWidth` for all `scenery/Text` and `scenery/RichText` instances.  You can choose values empirically.

For example, here's how this can be addressed in XrayControlPanel.js:

```js
      const textOptions = {
        maxWidth: 200
      };
```

... and then pass `textOptions` to all instances of `RichText`, e.g.:

```js
      const angleTitle = new RichText( incidentAngleString, textOptions );
      const wavelengthTitle = new RichText( wavelengthString, textOptions );
      const horizontalTitle = new RichText( horizontalRaysString, textOptions );
      const verticalTitle = new RichText( verticalRaysString, textOptions );
      const aLatticeTitle = new RichText( aLatticeConstantString, textOptions );
      const bLatticeTitle = new RichText( bLatticeConstantString, textOptions );
...
      const animateCheckbox = new Checkbox( new RichText(animateString, textOptions), model.animateProperty );
      const pathDifferenceCheckbox = new Checkbox( new RichText(pathDifferenceString, textOptions), model.pathDifferenceProperty );
      const showWaveFrontsCheckbox = new Checkbox( new RichText(showWavefrontsString, textOptions), model.showWaveFrontsProperty );
      const showParmsCheckbox = new Checkbox( new RichText( showParametersString, textOptions ), model.showParmsProperty );
```

Which results in:

<img width="1178" alt="screenshot_361" src="https://user-images.githubusercontent.com/3046552/83439981-5703a280-a401-11ea-9d40-b142f61357fc.png">

You might want to address #5 before addressing this issue, because CrystalNode.js will need to handle `maxWidth` similarly.

**Comment by heldentodd** [comment]
Done.

Several maxwidth values have been added or decreased to better handle long strings.
