### ISSUE TITLE
sim title and repository name

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#8]
Related to #1 (code review).

> - [ ] The repository name should correspond to the sim title. For example, if the sim title is "Wave Interference", then the repository name should be "wave-interference".

This sim is currently titled "Xray Diffraction".   Pedantically, "Xray" should be "X-ray".   So I think that PhET would likely request that change.   

If you do change the title, then it's a little unclear whether you need to rename the repository. PhET convention is that hypen in repository names is used as a separator, not necessarily as the literal "-" in a word.   I can see arguments for both "xray-diffraction" and "x-ray-diffraction", and I'll leave that choice up to you.

You definitely do not need to change class names like `XrayDiffractionScreenView`. Hypen is not an allowed character in class names.

**Comment by heldentodd** [comment]
I change the title to X-Ray Diffraction (title case). It would look prettier as X-ray, but then we shouldn't capitalize diffraction. I'll hold off on changing to x-ray-diffraction for now. The other way feels better mentally. In the end, I'll do whatever PhET asks.
